from BooleanABR import BooleanABR
from NormalABR import NormalABR

normalABR = NormalABR()
normalABR.insert(7)
normalABR.insert(1)
normalABR.insert(4)
normalABR.insert(10)
normalABR.insert(8)
print("albero ordinato: ")
normalABR.inorder()
normalABR.delete(4)
print("\nalbero dopo cancellazione: ")
normalABR.inorder()

booleanABR = BooleanABR()
booleanABR.insert(2)
booleanABR.insert(8)
booleanABR.insert(5)
print("\nalbero ordinato: ")
normalABR.inorder()
booleanABR.delete(8)
print("\nalbero dopo cancellazione: ")
normalABR.inorder()
booleanABR.insert(3)
print("albero ordinato: ")
normalABR.inorder()