from BooleanABR import BooleanABR
from ListABR import ListABR
from NormalABR import NormalABR

normalABR = NormalABR()
normalABR.insert(7)
normalABR.insert(1)
normalABR.insert(4)
normalABR.insert(10)
normalABR.insert(8)
normalABR.insert(7)
print("albero ordinato: ")
normalABR.inorder()
normalABR.delete(4)
print("\nalbero dopo cancellazione: ")
normalABR.inorder()
print("\nnodo presente: ", normalABR.find(1))
print("\nnodo presente: ", normalABR.find(5))

booleanABR = BooleanABR()
booleanABR.insert(2)
booleanABR.insert(8)
booleanABR.insert(5)
booleanABR.insert(8)
print("\nalbero ordinato: ")
booleanABR.inorder()
booleanABR.delete(8)
print("\nalbero dopo cancellazione: ")
booleanABR.inorder()
booleanABR.insert(3)
print("\nalbero ordinato: ")
booleanABR.inorder()
print("\nnodo presente: ", booleanABR.find(8))
print("\nnodo presente: ", booleanABR.find(5))

listABR = ListABR()
listABR.insert(11)
listABR.insert(12)
listABR.insert(4)
listABR.insert(10)
listABR.insert(8)
listABR.insert(11)
listABR.insert(11)
print("\nalbero ordinato: ")
listABR.inorder()
listABR.delete(11)
listABR.delete(11)
print("\nalbero dopo cancellazione: ")
listABR.inorder()
print("\nnodo presente: ", listABR.find(12))
print("\nnodo presente: ", listABR.find(1))